[package]
name = "asistencia"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
chrono = "0.4.39"
rust_xlsxwriter = "0.80.0"
serde = {version="1.0.217",features=["derive"]}
serde_json = "1.0.134"
sqlite = "0.36.1"
